export const users = [
    {
        id: 1,
        name: "Alice Johnson",
        email: "alice@example.com",
        password: "hashed_password_1",
        createdAt: new Date("2023-01-01T10:00:00Z"),
        projectIds: [1, 2],
    },
    {
        id: 2,
        name: "Bob Smith",
        email: "bob@example.com",
        password: "hashed_password_2",
        createdAt: new Date("2023-01-02T10:00:00Z"),
        projectIds: [1],
    },
    {
        id: 3,
        name: "Charlie Brown",
        email: "charlie@example.com",
        password: "hashed_password_3",
        createdAt: new Date("2023-01-03T10:00:00Z"),
        projectIds: [2, 3],
    },
    {
        id: 4,
        name: "Diana Prince",
        email: "diana@example.com",
        password: "hashed_password_4",
        createdAt: new Date("2023-01-04T10:00:00Z"),
        projectIds: [3],
    },
];

export const projects = [
    {
        id: 1,
        name: "Website Redesign",
        description: "A project focused on redesigning the company website to improve user experience and accessibility.",
        members: [1, 2],
        taskIds: [1, 2, 3],
        status: "active",
        meta: {
            createdBy: 1,
            createdAt: new Date("2023-01-01T10:00:00Z"),
            updatedAt: new Date("2023-01-10T10:00:00Z"),
        },
    },
    {
        id: 2,
        name: "API Development",
        description: "Development of a RESTful API to support mobile and web applications.",
        members: [1, 3],
        taskIds: [4, 5],
        status: "active",
        meta: {
            createdBy: 3,
            createdAt: new Date("2023-01-05T10:00:00Z"),
            updatedAt: new Date("2023-01-15T10:00:00Z"),
        },
    },
    {
        id: 3,
        name: "Mobile App Launch",
        description: "Preparation and execution of the launch for the new mobile application, including marketing and user feedback.",
        members: [3, 4],
        taskIds: [6, 7, 8],
        status: "completed",
        meta: {
            createdBy: 4,
            createdAt: new Date("2023-01-10T10:00:00Z"),
            updatedAt: new Date("2023-01-20T10:00:00Z"),
        },
    },
];

export const tasks = [
    {
        id: 1,
        name: "Design Homepage",
        description: "Create a new design for the homepage that enhances user engagement and reflects the brand identity.",
        startTime: new Date("2023-01-01T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-05T10:00:00Z").toISOString(),
        status: "success",
        tags: ["urgent", "frontend"],
        projectId: 1,
        createdAt: new Date("2023-01-01T10:00:00Z").toISOString(),
        createdBy: 1,
        updatedAt: new Date("2023-01-02T10:00:00Z").toISOString(),
        updatedBy: 1,
    },
    {
        id: 2,
        name: "Implement User Authentication",
        description: "Develop user authentication features including login, registration, and password recovery.",
        startTime: new Date("2023-01-02T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-06T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["backend"],
        projectId: 1,
        createdAt: new Date("2023-01-02T10:00:00Z").toISOString(),
        createdBy: 2,
        updatedAt: new Date("2023-01-03T10:00:00Z").toISOString(),
        updatedBy: 2,
    },
    {
        id: 3,
        name: "Create API Endpoints",
        description: "Develop the necessary API endpoints for user data retrieval and manipulation.",
        startTime: new Date("2023-01-03T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-07T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["design"],
        projectId: 1,
        createdAt: new Date("2023-01-03T10:00:00Z").toISOString(),
        createdBy: 1,
        updatedAt: new Date("2023-01-04T10:00:00Z").toISOString(),
        updatedBy: 1,
    },
    {
        id: 4,
        name: "Testing API Functionality",
        description: "Conduct thorough testing of the API to ensure all endpoints function correctly and handle errors gracefully.",
        startTime: new Date("2023-01-05T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-10T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["testing"],
        projectId: 2,
        createdAt: new Date("2023-01-05T10:00:00Z").toISOString(),
        createdBy: 3,
        updatedAt: new Date("2023-01-06T10:00:00Z").toISOString(),
        updatedBy: 3,
    },
    {
        id: 5,
        name: "Write API Documentation",
        description: "Create comprehensive documentation for the API, including usage examples and error handling.",
        startTime: new Date("2023-01-06T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-12T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["documentation"],
        projectId: 2,
        createdAt: new Date("2023-01-06T10:00:00Z").toISOString(),
        createdBy: 3,
        updatedAt: new Date("2023-01-07T10:00:00Z").toISOString(),
        updatedBy: 3,
    },
    {
        id: 6,
        name: "Develop Mobile App UI",
        description: "Design and implement the user interface for the mobile application, ensuring a seamless user experience.",
        startTime: new Date("2023-01-10T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-15T10:00:00Z").toISOString(),
        status: "success",
        tags: ["frontend"],
        projectId: 3,
        createdAt: new Date("2023-01-10T10:00:00Z").toISOString(),
        createdBy: 4,
        updatedAt: new Date("2023-01-11T10:00:00Z").toISOString(),
        updatedBy: 4,
    },
    {
        id: 7,
        name: "Conduct User Testing",
        description: "Gather user feedback on the mobile app to identify areas for improvement before launch.",
        startTime: new Date("2023-01-12T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-18T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["frontend"],
        projectId: 3,
        createdAt: new Date("2023-01-12T10:00:00Z").toISOString(),
        createdBy: 4,
        updatedAt: new Date("2023-01-13T10:00:00Z").toISOString(),
        updatedBy: 4,
    },
    {
        id: 8,
        name: "Launch Marketing Campaign",
        description: "Plan and execute a marketing campaign to promote the mobile app launch, targeting key demographics.",
        startTime: new Date("2023-01-15T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-20T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["marketing"],
        projectId: 3,
        createdAt: new Date("2023-01-15T10:00:00Z").toISOString(),
        createdBy: 4,
        updatedAt: new Date("2023-01-16T10:00:00Z").toISOString(),
        updatedBy: 4,
    },
    {
        id: 9,
        name: "Fix UI Bugs",
        description: "Identify and resolve any bugs in the user interface before the final release of the mobile app.",
        startTime: new Date("2023-01-16T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-22T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["frontend", "urgent"],
        projectId: 1,
        createdAt: new Date("2023-01-16T10:00:00Z").toISOString(),
        createdBy: 1,
        updatedAt: new Date("2023-01-17T10:00:00Z").toISOString(),
        updatedBy: 1,
    },
    {
        id: 10,
        name: "Final Review and Launch",
        description: "Conduct a final review of the mobile app and prepare for the official launch.",
        startTime: new Date("2023-01-18T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-25T10:00:00Z").toISOString(),
        status: "failed",
        tags: ["launch"],
        projectId: 2,
        createdAt: new Date("2023-01-18T10:00:00Z").toISOString(),
        createdBy: 2,
        updatedAt: new Date("2023-01-19T10:00:00Z").toISOString(),
        updatedBy: 2,
    },
    {
        id: 11,
        name: "Post-Launch Support",
        description: "Provide support and address any issues that arise after the mobile app launch.",
        startTime: new Date("2023-01-20T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-30T10:00:00Z").toISOString(),
        status: "success",
        tags: ["support"],
        projectId: 3,
        createdAt: new Date("2023-01-20T10:00:00Z").toISOString(),
        createdBy: 4,
        updatedAt: new Date("2023-01-21T10:00:00Z").toISOString(),
        updatedBy: 4,
    },
    {
        id: 12,
        name: "Create User Guides",
        description: "Develop user guides and tutorials to help users navigate the new mobile app effectively.",
        startTime: new Date("2023-01-22T10:00:00Z").toISOString(),
        deadline: new Date("2023-01-28T10:00:00Z").toISOString(),
        status: "ongoing",
        tags: ["documentation"],
        projectId: 1,
        createdAt: new Date("2023-01-22T10:00:00Z").toISOString(),
        createdBy: 1,
        updatedAt: new Date("2023-01-23T10:00:00Z").toISOString(),
        updatedBy: 1,
    },
];
